<a href="https://colab.research.google.com/github/mcash8/DVBS2X-DNN-Implementation/blob/main/Feed%20Forward%20NN/Doppler%20Effect/NN_CFO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Mount Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Imports

In [3]:
import os
import scipy.io as spio
import math
import time
import pandas as pd
from pandas import read_csv
import matplotlib.pyplot as plt
import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import MeanSquaredError

In [ ]:
#Train model
%cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data
start_time = time.time()

#parameters
num_classes = 2
batch_size = 64
epochs = 100

ratios = list(range(51,101))

for ratio in ratios: 
    matname = 'DVBS_dopp_ratio_%d' % (ratio)
    print(matname)
    mat = spio.loadmat(matname, squeeze_me=True)
    x_train = mat['x_train']
    x_valid = mat['val_data']
    y_valid = mat['val_target']
    y_train = mat['y_train']


    #cast to float32
    x_train = x_train.astype('float32')
    x_valid = x_valid.astype('float32')
    #x_test = x_test.astype('float32') 

    print(x_train.shape, 'train samples')
    print(x_valid.shape, 'valid samples')

    print(y_train.shape, 'train labels')
    print(y_valid.shape, 'valid labels')

    print('Label Examples:\n', y_train)
    print('Input Examples:\n', x_train)

    # Define the network
    model = Sequential()
    model.add(Dense(50, activation='elu', input_dim=18))
    model.add(Dense(50, activation='elu'))
    model.add(Dense(num_classes, activation='tanh'))

    model.summary()

    model.compile(loss=keras.metrics.mean_squared_error,
                optimizer=SGD(learning_rate=0.1),
                metrics=[keras.metrics.RootMeanSquaredError(name='rmse')])

    history = model.fit(x_train, y_train,
                        batch_size=batch_size,
                        epochs=epochs,
                        verbose=2,
                        validation_data=(x_valid, y_valid))

    elapsedTime = (time.time() - start_time)/60
    print("--- %.2f minutes ---" % elapsedTime)

    savename = 'model_dopp_ratio_%d.h5' % (ratio)
    model.save(savename)

Test trained models. Test sequence is same length and rotation as train data.

In [ ]:
ratios = list(range(51,101))

for ratio in ratios:
    model_name = 'model_dopp_ratio_%d.h5' % (ratio)
    folder_name = 'ratio_%d' % (ratio)

    #load trained model 
    %cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data
    model = tf.keras.models.load_model(model_name)

    %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data
    
    %cd $folder_name 
    
    for i in range(1,11): #loop over 10 test sequences 
        matname = 'DVBSAPSK_pred_ratio_%d_%d' % (ratio, i)

        mat = spio.loadmat(matname, squeeze_me=True) #load data
        x_test = mat['train_data']

        predictions = model.predict(x_test) #make predictions

        #save predictions 
        matname = 'DVBSAPSK_out_ratio_%d_%d.mat' % (ratio, i)
        spio.savemat(matname, {'pred': predictions})

    %cd ..
    

Test if sequence length significantly matters in NN output

In [ ]:
ratios = list(range(1,101))
#two foor loops, start with short length first, then long length 

main_folder = 'short_len'
for ratio in ratios:
    model_name = 'model_dopp_ratio_%d.h5' % (ratio)
    folder_name = 'ratio_%d' % (ratio)

    #load trained model 
    %cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data
    model = tf.keras.models.load_model(model_name)

    %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/

    %cd $main_folder
    %cd $folder_name 
    
    for i in range(1,11): #loop over 10 test sequences 
        matname = 'DVBSAPSK_pred_ratio_%d_%d' % (ratio, i)

        mat = spio.loadmat(matname, squeeze_me=True) #load data
        x_test = mat['train_data']

        predictions = model.predict(x_test) #make predictions

        #save predictions 
        matname = 'DVBSAPSK_out_ratio_%d_%d.mat' % (ratio, i)
        spio.savemat(matname, {'pred': predictions})

    %cd ..
    %cd ..

main_folder = 'med_len'
for ratio in ratios:
    model_name = 'model_dopp_ratio_%d.h5' % (ratio)
    folder_name = 'ratio_%d' % (ratio)

    #load trained model 
    %cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data
    model = tf.keras.models.load_model(model_name)

    %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/

    %cd $main_folder
    %cd $folder_name 
    
    for i in range(1,11): #loop over 10 test sequences 
        matname = 'DVBSAPSK_pred_ratio_%d_%d' % (ratio, i)

        mat = spio.loadmat(matname, squeeze_me=True) #load data
        x_test = mat['train_data']

        predictions = model.predict(x_test) #make predictions

        #save predictions 
        matname = 'DVBSAPSK_out_ratio_%d_%d.mat' % (ratio, i)
        spio.savemat(matname, {'pred': predictions})

    %cd ..
    %cd ..

main_folder = 'long_len'
for ratio in ratios:
    model_name = 'model_dopp_ratio_%d.h5' % (ratio)
    folder_name = 'ratio_%d' % (ratio)

    #load trained model 
    %cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data
    model = tf.keras.models.load_model(model_name)

    %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/

    %cd $main_folder
    %cd $folder_name 
    
    for i in range(1,11): #loop over 10 test sequences 
        matname = 'DVBSAPSK_pred_ratio_%d_%d' % (ratio, i)

        mat = spio.loadmat(matname, squeeze_me=True) #load data
        x_test = mat['train_data']

        predictions = model.predict(x_test) #make predictions

        #save predictions 
        matname = 'DVBSAPSK_out_ratio_%d_%d.mat' % (ratio, i)
        spio.savemat(matname, {'pred': predictions})

    %cd ..
    %cd ..

Test robustness of NN

In [ ]:
ratios = list(range(1,41))
trained_models = list(range(1,41))

main_folder = 'robust_test'

%cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data
%mkdir $main_folder

for trained_model in trained_models:
    %cd $main_folder 
    main_folder_store = 'trained_model_%d_robust' % (trained_model)
    #folder for storing predictions from trained model at set alpha
    %mkdir $main_folder_store

    #load trained model 
    %cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data
    model_name = 'model_dopp_ratio_%d.h5' % (trained_model)
    model = tf.keras.models.load_model(model_name)

    for ratio in ratios: 
        #naviagte to test data folder
        %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data
        #load data to predict on
        folder_name = 'ratio_%d' % (ratio)
        %cd $folder_name

        for i in range(1,11): #loop over 10 test sequences 
            matname = 'DVBSAPSK_pred_ratio_%d_%d' % (ratio, i)

            mat = spio.loadmat(matname, squeeze_me=True) #load data
            x_test = mat['train_data']

            predictions = model.predict(x_test) #make predictions

            #save predictions 
            %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data
            %cd $main_folder 
            %cd $main_folder_store

            matname = 'DVBSAPSK_out_ratio_%d_%d.mat' % (ratio, i)
            spio.savemat(matname, {'pred': predictions})

            %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data
            %cd $folder_name
        %cd ..

This section will train a NN on varying sequence lengths at one frequency offset

In [ ]:
#Train model
%cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data
main_folder = 'train_diff_lengths_model_save'
%mkdir $main_folder

start_time = time.time()

#parameters
num_classes = 2
batch_size = 64
epochs = 100

ratios = list(range(91,101))

for ratio in ratios: 
    %cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data
    %cd diff_train_lengths

    matname = 'DVBS_dopp_ratio_%d' % (ratio)
    print(matname)
    mat = spio.loadmat(matname, squeeze_me=True)
    x_train = mat['x_train']
    x_valid = mat['val_data']
    y_valid = mat['val_target']
    y_train = mat['y_train']


    #cast to float32
    x_train = x_train.astype('float32')
    x_valid = x_valid.astype('float32')
    #x_test = x_test.astype('float32') 

    print(x_train.shape, 'train samples')
    print(x_valid.shape, 'valid samples')

    print(y_train.shape, 'train labels')
    print(y_valid.shape, 'valid labels')

    print('Label Examples:\n', y_train)
    print('Input Examples:\n', x_train)

    # Define the network
    model = Sequential()
    model.add(Dense(50, activation='elu', input_dim=18))
    model.add(Dense(50, activation='elu'))
    model.add(Dense(num_classes, activation='tanh'))

    model.summary()

    model.compile(loss=keras.metrics.mean_squared_error,
                optimizer=SGD(learning_rate=0.1),
                metrics=[keras.metrics.RootMeanSquaredError(name='rmse')])

    history = model.fit(x_train, y_train,
                        batch_size=batch_size,
                        epochs=epochs,
                        verbose=2,
                        validation_data=(x_valid, y_valid))

    elapsedTime = (time.time() - start_time)/60
    print("--- %.2f minutes ---" % elapsedTime)

    savename = 'model_dopp_ratio_%d.h5' % (ratio)
    %cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data
    %cd $main_folder
    model.save(savename)
    %cd .. 

/content/drive/My Drive/NN Input/Doppler/Train Data
mkdir: cannot create directory ‘train_diff_lengths_model_save’: File exists
/content/drive/My Drive/NN Input/Doppler/Train Data
/content/drive/My Drive/NN Input/Doppler/Train Data/diff_train_lengths
DVBS_dopp_ratio_91
(276000, 18) train samples
(2000, 18) valid samples
(276000, 2) train labels
(2000, 2) valid labels
Label Examples:
 [[-0.25882 -0.96593]
 [-0.70711  0.70711]
 [-0.70711 -0.70711]
 ...
 [-0.25882  0.96593]
 [-0.22448 -0.22448]
 [-0.96593  0.25882]]
Input Examples:
 [[ 0.96607  0.96622  0.22409 ... -0.22537 -0.70386  0.71074]
 [ 0.96622  0.22409 -0.25661 ... -0.70386  0.71074  0.71114]
 [ 0.22409 -0.25661 -0.70913 ...  0.71074  0.71114 -0.22589]
 ...
 [-0.80088 -0.99306  0.25447 ... -0.22448 -0.25827 -0.22473]
 [-0.99306  0.25447 -0.91836 ... -0.25827 -0.22473  0.70589]
 [ 0.25447 -0.91836  0.25468 ... -0.22473  0.70589 -0.70549]]
Model: "sequential"
_________________________________________________________________
 Layer

Test models trained on varying sequence lengths 

In [7]:
ratios = list(range(1,51))
#two for loops, start with short length first, then long length
%cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/
%mkdir diff_length_train_res

#1,500 symb
for ratio in ratios:
    model_name = 'model_dopp_ratio_%d.h5' % (ratio)
    folder_name = 'ratio_%d' % (ratio)

    #load trained model 
    %cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data/train_diff_lengths_model_save
    model = tf.keras.models.load_model(model_name) 
    
    for i in range(1,11): #loop over 10 test sequences 
        
        %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/
        %cd $folder_name 

        matname = 'DVBSAPSK_pred_ratio_%d_%d' % (ratio, i)

        mat = spio.loadmat(matname, squeeze_me=True) #load data
        x_test = mat['train_data']

        predictions = model.predict(x_test) #make predictions

        #save predictions 
        %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/
        %cd diff_length_train_res
        matname = 'DVBSAPSK_out_ratio_%d_%d.mat' % (ratio, i)
        spio.savemat(matname, {'pred': predictions})


main_folder = 'short_len'
%cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/
%cd diff_length_train_res
%mkdir $main_folder 

for ratio in ratios:
    model_name = 'model_dopp_ratio_%d.h5' % (ratio)
    folder_name = 'ratio_%d' % (ratio)

    #load trained model 
    %cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data/train_diff_lengths_model_save
    model = tf.keras.models.load_model(model_name)
 
    
    for i in range(1,11): #loop over 10 test sequences 
        
        %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/
        %cd $folder_name 

        matname = 'DVBSAPSK_pred_ratio_%d_%d' % (ratio, i)

        mat = spio.loadmat(matname, squeeze_me=True) #load data
        x_test = mat['train_data']

        predictions = model.predict(x_test) #make predictions

        #save predictions 
        %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/
        %cd diff_length_train_res
        %cd $main_folder
        matname = 'DVBSAPSK_out_ratio_%d_%d.mat' % (ratio, i)
        spio.savemat(matname, {'pred': predictions})


main_folder = 'med_len'
%cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/
%cd diff_length_train_res
%mkdir $main_folder 

for ratio in ratios:
    model_name = 'model_dopp_ratio_%d.h5' % (ratio)
    folder_name = 'ratio_%d' % (ratio)

    #load trained model 
    %cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data/train_diff_lengths_model_save
    model = tf.keras.models.load_model(model_name)
    
    for i in range(1,11): #loop over 10 test sequences 
    
        %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/
        %cd $folder_name 

        matname = 'DVBSAPSK_pred_ratio_%d_%d' % (ratio, i)

        mat = spio.loadmat(matname, squeeze_me=True) #load data
        x_test = mat['train_data']

        predictions = model.predict(x_test) #make predictions

        #save predictions 
        %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/
        %cd diff_length_train_res
        %cd $main_folder
        matname = 'DVBSAPSK_out_ratio_%d_%d.mat' % (ratio, i)
        spio.savemat(matname, {'pred': predictions})

main_folder = 'long_len'
%cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/
%cd diff_length_train_res
%mkdir $main_folder 

for ratio in ratios:
    model_name = 'model_dopp_ratio_%d.h5' % (ratio)
    folder_name = 'ratio_%d' % (ratio)

    #load trained model 
    %cd /content/drive/My Drive/NN\ Input/Doppler/Train\ Data/train_diff_lengths_model_save
    model = tf.keras.models.load_model(model_name)

    for i in range(1,11): #loop over 10 test sequences 
        %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/
        %cd $folder_name 

        matname = 'DVBSAPSK_pred_ratio_%d_%d' % (ratio, i)

        mat = spio.loadmat(matname, squeeze_me=True) #load data
        x_test = mat['train_data']

        predictions = model.predict(x_test) #make predictions

        #save predictions 
        %cd /content/drive/My Drive/NN\ Input/Doppler/Test\ Data/Test\ Data/
        %cd diff_length_train_res
        %cd $main_folder
        matname = 'DVBSAPSK_out_ratio_%d_%d.mat' % (ratio, i)
        spio.savemat(matname, {'pred': predictions})

Streaming output truncated to the last 5000 lines.
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data/ratio_3
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data/diff_length_train_res
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data/diff_length_train_res/med_len
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data/ratio_3
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data/diff_length_train_res
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data/diff_length_train_res/med_len
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data/ratio_3
/content/drive/My Drive/NN Input/Doppler/Test Data/Test Data
/content/drive/My Drive/NN I